# appspec.yml

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/playground-logging # 프로젝트 이름
    overwrite: yes

permissions: #권한 허용
  - object: /home/ubuntu/playground-logging/
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks: #scripts
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 180
      runas: ec2-user
    - location: scripts/health_check.sh
      timeout: 180
      runas: ec2-user
    - location: scripts/switch.sh
      timeout: 180
      runas: ec2-user